name: Build and Deploy Elm to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Elm
        uses: dillonkearns/elm-tooling-action@v1

      - name: Build Elm to docs/
        run: elm make src/Main.elm --output=docs/main.js

